name: Build and Deploy to Neocities

on:
  push:
  workflow_dispatch:

env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}

jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: https://git.chobble.com/mirrored/checkout@v4

      - name: Build
        run: nix-build

      - name: Deploy
        run: neocities push --prune result
